---
- name: Ensure Network Security Group Exists
  azure_rm_securitygroup:
    name: "{{ az_network_security_group_name }}"
    resource_group: "{{ az_resource_group_name }}"
    state: "present"
    tenant: "{{ azure_tenant_id }}"
    subscription_id: "{{ azure_subscription_id }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    tags:
      Owner: "{{ azure_tag.Owner }}"
      Company: "{{ azure_tag.Company }}"
      Project: "{{ azure_tag.Project }}"
  loop: "{{ azure_tags }}"
  loop_control:
    loop_var: azure_tag
    label: "{{ azure_tag.name }}"
  register: CreatedNetworkSecurityGroup

# - name: Ensure Rules Exists in Network Security Group
#   azure_rm_securitygroup:
#     name:
#     resource_group:
#     rules:
#       - name: "{{ nsg_rule.name }}"
#         protocol: "{{ nsg_rule.protocol }}"
#         destination_port_range: "{{ nsg_rule.destination_port_range }}"
#         access: "{{ nsg_rule.access }}"
#         priority: "{{ nsg_rule.priority }}"
#         direction: "{{ nsg_rule.direction }}"
#   loop:
#     - "{{ az_network_security_group_rules }}"
#   loop_control:
#     loop_var: nsg_rule
#     label: "{{ nsg_rule.name }}"
...
