---
- name: Ensure Network Security Group Exists
  azure_rm_securitygroup:
    name: "{{ az_network_security_group_name }}"
    resource_group: "{{ az_resource_group_name }}"
    state: "present"
    tenant: "{{ azure_tenant_id }}"
    subscription_id: "{{ azure_subscription_id }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    tags:
      Owner: "{{ azure_tag.Owner }}"
      Company: "{{ azure_tag.Company }}"
      Project: "{{ azure_tag.Project }}"
  loop: "{{ azure_tags }}"
  loop_control:
    loop_var: azure_tag
    label: "{{ azure_tag.name }}"
  register: CreatedNetworkSecurityGroup

- name: Ensure Rules Exists in Network Security Group
  azure_rm_securitygroup: 
    name: "{{ az_network_security_group_name }}"
    resource_group: "{{ az_resource_group_name }}"
    rules:
      - name: "{{ nsg_rule.value.name }}"
        protocol: "{{ nsg_rule.value.protocol }}"
        destination_port_range: "{{ nsg_rule.value.destination_port_range }}"
        access: "{{ nsg_rule.value.access }}"
        priority: "{{ nsg_rule.value.priority }}"
        direction: "{{ nsg_rule.value.direction }}"
    tenant: "{{ azure_tenant_id }}"
    subscription_id: "{{ azure_subscription_id }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
  loop: "{{ az_network_security_group_rules|dict2items }}"
  loop_control:
    loop_var: nsg_rule
    label: "{{ nsg_rule.value.name }}"
...
