---
- name: Ensure Network Security Group Exists
  azure_rm_securitygroup:
    name: "{{ az_network_security_group_name }}"
    resource_group: "{{ az_resource_group_name }}"
    state: "present"
    rules: "{{ az_network_security_group_rules }}"
    tenant: "{{ azure_tenant_id }}"
    subscription_id: "{{ azure_subscription_id }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    tags:
      Owner: "{{ azure_tag.Owner }}"
      Company: "{{ azure_tag.Company }}"
      Project: "{{ azure_tag.Project }}"
  loop: "{{ azure_tags }}"
  loop_control:
    loop_var: azure_tag
    label: "{{ azure_tag.name }}"
  register: CreatedNetworkSecurityGroup
...
